runtime: python39  # The runtime for your application. Choose the appropriate runtime for your programming language (e.g., python39, nodejs14, java11).

instance_class: F2  # Set the instance class based on your application's resource requirements.

automatic_scaling:
  target_cpu_utilization: 0.65  # Adjust the target CPU utilization for automatic scaling.
  min_instances: 1
  max_instances: 10  # Set the maximum number of instances.

handlers:
- url: /static
  static_dir: static  # Map the /static URL path to the 'static' directory for serving static files.

- url: /.*
  script: auto  # Map all other URLs to the appropriate script or runtime (auto detects).

env_variables:
  YOUR_ENV_VARIABLE: 'value'  # Define environment variables for your application.

# Add additional configuration settings as needed.
